DATA:
    DATASET: ntu60
    INPUT_SIZE: 224
    LABEL_LIST: /path/to/novel_class_labels.csv
    NUM_CLASSES: 12
    NUM_FRAMES: 16
    ROOT: /path/to/ntu/NTU60_224x224/rgb
    TRAIN_FILE: /path/to/ntu/zsl_48-12_ntu60_base_train_data.csv 
    VAL_FILE: /path/to/ntu/zsl_48-12_ntu60_novel_data.csv 
    SKELETON_DATA: /path/to/ntu/processed_skeleton_data/NTU60_CS.npz

SAVE_FREQ: 5 
MODEL:
    ARCH: ViT-B/16
    POSE_MODEL: 'trainers.Hyperformer.Hyperformer_Model'
    GRAPH: 'graph.ntu_rgb_d.Graph'
    # graph_args:
    LABELING_MODE: 'spatial'
    JOINT_LABEL: [0, 4, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 2, 3, 3, 3, 1, 0, 1, 0, 1]

TRAIN:
    EPOCHS: 30 
    BATCH_SIZE: 4 # BS 512 (Effective BS=64)
    ACCUMULATION_STEPS: 16  # for 8 gpus this should be 16
    LR: 2.2e-05 
    WARMUP_EPOCHS: 5
TEST:
    MULTI_VIEW_INFERENCE: False # By default in ViFi-Clip this is set to true
TRAINER:
  SKI_VLM:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
